### ISSUE TITLE
Could not load file or assembly 'Microsoft.Azure.Documents.Client, Version=2.1.0.0

### ISSUE THREAD

**Issue by echan-cleardent** [goto10hq/NLog.DocumentDB#3]
My project is .net core 2.0 and when using nlog.documentDB to log, I keep getting the error:
`Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Azure.Documents.Client, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.`
I am using Nlog.DocumentDBTarget v1.2.0

**Comment by frohikey** [comment]
Library targets .NET FW 4.5.2 so compatibility with .NET Core is always iffy 😐 I did some local tests with .NET Core and yeah... I got ``System.Configuration.ConfigurationManager``` cannot be loaded error.

I'm gonna create a .NET Standard version and test it against .NET FW / Core. Gimmie 1-2 days.

**Comment by frohikey** [comment]
Hurray! Feel free to test it. It worked great for me.

``Install-Package Nlog.DocumentDBTarget -Version 2.0.0``

There's only one __very__ small problem. If you use ASP.NET Core it's impossible to set ``Application`` from ``SiteName`` easily. Nlog has two packages (NLog.Web.AspNetCore, NLog.Web). So I'd make 2 packages as well. Basically it's impossible to running environment (IIS, Kestrel) easily so at the moment If Application is not set in layout I always use process name (which was a fail-over in prev version anyway).

**Comment by echan-cleardent** [comment]
Awesome works great for me! Thanks a lot! I am not using `Application` so it's ok for me.
