### ISSUE TITLE
Setting the dynamic values to target attributes

### ISSUE THREAD

**Issue by Nagaraju-Pateti** [goto10hq/NLog.DocumentDB#5]
`<target name="main" type="DocumentDB" endPoint="Dynamic value" authorizationKey="Dynamic values">`
Basically i want set the endPoint from appsettings/gdc but none of them working.``

**Comment by Nagaraju-Pateti** [comment]
@frohikey , Did you get any chance look into the above one?

**Comment by frohikey** [comment]
You wanna get you values from some secure vault instead of "hardcore" values in nlog configuration file. Right?

The easiest way is to create a configuration manually. Small snippet:

```
var config = new NLog.Config.LoggingConfiguration();

var cosmos = new Nlog.DocumentDBTarget.DocumentDBTarget
{     
    EndPoint = "https://myendpoint.documents.azure.com:443",
    AuthorizationKey = "mykey==",
    Database = "mydb",
    Collection = "mycollection"
};


config.AddRule(LogLevel.Info, LogLevel.Fatal, cosmos);

LogManager.Configuration = config;

_logger.Error("Hello Kitty!");
```

**Comment by Nagaraju-Pateti** [comment]
@frohikey   Thanks! Man, for a quick replay will try it and let you know the results.

**Comment by Nagaraju-Pateti** [comment]
@frohikey , please below refer link for our exact issue

https://stackoverflow.com/questions/17062653/passing-values-to-nlog-custom-target 
Can we change the data type of EndPoint and AuthKey as mentioned in above url?

**Comment by frohikey** [comment]
EndPoint and AuthKey is a basically connection string for CosmosDb (DocumentDb). So I'm not sure what you are trying to achieve. And it's really the best way to set these two ones in the init phase (see my first answer).

If you want to set them later. You can inherit from [DocumentDBTarget.cs](https://github.com/goto10hq/NLog.DocumentDB/blob/master/NLog.DocumentDBTarget/DocumentDBTarget.cs) and make your own target class. Override `InitializeTarget` and set these values (ie create connection string) there.

Or just fork this repo and modify it as you wish. This small lib was meant to be a fast and simple solution with kinda narrow possibilities for customization.

**Comment by Nagaraju-Pateti** [comment]
> You wanna get you values from some secure vault instead of "hardcore" values in nlog configuration file. Right?
> 
> The easiest way is to create a configuration manually. Small snippet:
> 
> ```
> var config = new NLog.Config.LoggingConfiguration();
> 
> var cosmos = new Nlog.DocumentDBTarget.DocumentDBTarget
> {     
>     EndPoint = "https://myendpoint.documents.azure.com:443",
>     AuthorizationKey = "mykey==",
>     Database = "mydb",
>     Collection = "mycollection"
> };
> 
> 
> config.AddRule(LogLevel.Info, LogLevel.Fatal, cosmos);
> 
> LogManager.Configuration = config;
> 
> _logger.Error("Hello Kitty!");
> ```

I fixed the issue with above one
